version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g @angular/cli@latest
      - npm -v
      - ng version
  build:
    commands:
      - ng build --configuration=production --build-optimizer
  post_build:
    commands:
      - aws s3 sync dist/ s3://www.cloudfacilities.click --delete
